name: blog-medico-vintage

services:
  - name: web
    github:
      repo: isacioutp/blogapppython
      branch: deploy-do
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
